const copy = {
  en: { models: 'Models', updates: 'Changelog', start: 'Get started', docs: 'Read documentation', eyebrow: 'One API for leading AI models', headline: 'Make every AI call simple and reliable', description: 'LLMAPI gives teams and developers a unified, stable and secure AI model service. Focus on your product and leave the complexity to us.', ready: 'Request ready', availability: 'Service availability', providers: 'Leading model providers', latency: 'Low-latency access', support: 'Reliable service', capabilityEyebrow: 'Built for production', capabilityTitle: 'One platform for the complete AI workflow', capabilityText: 'From model choice to usage insights, achieve more with less complexity.', featureOne: 'Unified API', featureOneText: 'Use a familiar interface and switch freely between models and providers.', featureTwo: 'Reliable by design', featureTwoText: 'Intelligent routing and failover keep critical services available.', featureThree: 'Clear control', featureThreeText: 'Every request is visible, from usage and cost to model performance.', modelEyebrow: 'Capabilities that keep expanding', modelTitle: 'Choose the model that fits', modelFast: 'Fast, versatile multimodal intelligence', modelReasoning: 'Long context and complex reasoning', modelNative: 'Native multimodality and efficiency', calloutEyebrow: 'Build now', calloutTitle: 'Keep your focus on what matters.', calloutText: 'Create an account and call the AI models you need in minutes.', createAccount: 'Create a free account', faq: 'FAQ', about: 'About us' },
  zh: { models: '模型广场', updates: '更新日志', start: '立即开始', docs: '阅读文档', eyebrow: '一个接口，连接所有主流 AI 模型', headline: '让每一次智能调用，都简单可靠', description: 'LLMAPI 为团队与开发者提供统一、稳定、安全的 AI 模型服务。专注产品创新，其余交给我们。', ready: '请求已准备就绪', availability: '服务可用性', providers: '主流模型提供商', latency: '低延迟接入体验', support: '持续稳定服务', capabilityEyebrow: '为生产环境而生', capabilityTitle: '一个平台，承载完整的 AI 工作流', capabilityText: '从模型选择到调用分析，用更少的复杂度获得更好的体验。', featureOne: '统一 API', featureOneText: '使用熟悉的接口，在多个模型与供应商之间自由切换。', featureTwo: '稳定可靠', featureTwoText: '智能调度与故障切换，保障关键业务持续可用。', featureThree: '清晰可控', featureThreeText: '从用量、费用到模型表现，每一笔调用都有据可查。', modelEyebrow: '不断扩展的能力边界', modelTitle: '选择适合你的模型', modelFast: '快速、全能的多模态能力', modelReasoning: '长文本与复杂推理', modelNative: '原生多模态与高效执行', calloutEyebrow: '现在开始构建', calloutTitle: '把精力留给真正重要的产品。', calloutText: '创建账号，几分钟内开始调用你需要的 AI 模型。', createAccount: '创建免费账号', faq: '常见问答', about: '关于我们' }
}
for (const lang of ['zh-TW', 'ja', 'fr', 'ru', 'vi']) copy[lang] = copy.en
function setLanguage(language) { const strings = copy[language] || copy[language?.split('-')[0]] || copy.en; document.documentElement.lang = language || 'en'; document.querySelectorAll('[data-i18n]').forEach((node) => { node.textContent = strings[node.dataset.i18n] || copy.en[node.dataset.i18n] || node.textContent }) }
function setTheme(theme) { document.documentElement.dataset.theme = theme; document.documentElement.style.colorScheme = theme === 'dark' ? 'dark' : 'light' }
window.addEventListener('message', (event) => { if (event.data?.lang) setLanguage(event.data.lang); if (event.data?.themeMode) setTheme(event.data.themeMode) })
document.querySelectorAll('.dots button').forEach((dot, index) => dot.addEventListener('click', () => { document.querySelectorAll('.model-card').forEach((card, cardIndex) => card.classList.toggle('active', cardIndex === index)); document.querySelectorAll('.dots button').forEach((button, buttonIndex) => button.classList.toggle('active', buttonIndex === index)) }))
document.querySelector('.previous').addEventListener('click', () => document.querySelectorAll('.dots button')[(Array.from(document.querySelectorAll('.dots button')).findIndex((button) => button.classList.contains('active')) + 2) % 3].click())
document.querySelector('.next').addEventListener('click', () => document.querySelectorAll('.dots button')[(Array.from(document.querySelectorAll('.dots button')).findIndex((button) => button.classList.contains('active')) + 1) % 3].click())
document.getElementById('year').textContent = new Date().getFullYear()
setLanguage(new URLSearchParams(location.search).get('lang') || navigator.language)
